#!/usr/bin/env python
#
# $Id: gale_const.py,v 1.1.1.1 2002/09/03 18:21:25 tlau Exp $
#

GALE_RSA_MODULUS_BITS = 1024
GALE_RSA_MODULUS_LEN = ((GALE_RSA_MODULUS_BITS + 7) / 8)
GALE_RSA_PRIME_BITS = ((GALE_RSA_MODULUS_BITS + 1) / 2)
GALE_RSA_PRIME_LEN = ((GALE_RSA_PRIME_BITS + 7) / 8)
GALE_ENCRYPTED_KEY_LEN = GALE_RSA_MODULUS_LEN
GALE_SIGNATURE_LEN = GALE_RSA_MODULUS_LEN

